sudo: false
language: python
python:
  - "2.7"
  - "3.5"
matrix:
  allow_failures:
    - python: "3.5"
before_script:
  - mysql -e "create database IF NOT EXISTS test;" -uroot
script:
  - ./run-tests.py
notifications:
  email:
    on_success: never
    on_failure: always
